{ pkgs, inputs, ... }:

{
  home.username = "jose";
  home.homeDirectory = "/home/jose";
  home.stateVersion = "26.05";

  imports = [
    ./nixvim.nix
    inputs.noctalia.homeModules.default
  ];

  programs.home-manager.enable = true;

  programs.bash = {
    enable = true;

    initExtra = ''
      __git_prompt() {
        local ref
        ref=$(git symbolic-ref --quiet --short HEAD 2>/dev/null) || ref=$(git rev-parse --short HEAD 2>/dev/null) || return
        local dirty=""
        [ -n "$(git status --porcelain 2>/dev/null)" ] && dirty="*"
        printf ' (%s%s)' "$ref" "$dirty"
      }

      __nix_shell_prompt() {
        [ -n "''${IN_NIX_SHELL:-}" ] && printf ' [nix-shell]'
      }

      PS1='\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\[\e[1;33m\]$(__git_prompt)\[\e[0m\]\[\e[1;36m\]$(__nix_shell_prompt)\[\e[0m\]\$ '
    '';
  };

  programs.kitty = {
    enable = true;

    font = {
      name = "AdwaitaMono Nerd Font";
      size = 17;
    };

    settings = {
      enable_audio_bell = false;
    };
  };

  programs.git = {
    enable = true;

    settings = {
      user = {
        name = "jose tapadas alves";
        email = "jose.tapadas@gmail.com";
        signingkey = "/home/jose/.ssh/id_ed25519.pub";
      };

      init.defaultBranch = "main";
      pull.rebase = false;
      push.autoSetupRemote = true;
      fetch.prune = true;
      gpg.format = "ssh";
      commit.gpgsign = true;
      tag.gpgsign = true;
    };
  };

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;

    settings."*" = {
      AddKeysToAgent = "yes";
    };
  };

  programs.pi-coding-agent = {
    enable = true;

    extraPackages = with pkgs; [
      git
      gh
      jq
      ripgrep
      fd
      tree

      nix
      nixd
      nixfmt-rfc-style
      statix
      deadnix
    ];
  };

  home.packages = with pkgs; [
    # AI coding agents and their terminal runtime.
    herdr
    github-copilot-cli
    claude-code

    # Terminal and desktop utilities.
    kitty
    foot
    fuzzel
    wl-clipboard
    grim
    slurp
    libnotify

    # Desktop applications.
    obsidian

    # General development and repository tools.
    git
    gh
    lazygit
    openssh
    jq
    ripgrep
    fd
    tree

    # Nix development, formatting, and static analysis.
    nixd
    nixfmt-rfc-style
    statix
    deadnix
  ];

  home.pointerCursor = {
    enable = true;
    gtk.enable = true;
    x11.enable = true;

    package = pkgs.adwaita-icon-theme;
    name = "Adwaita";
    size = 24;
  };

  gtk = {
    enable = true;

    iconTheme = {
      package = pkgs.adwaita-icon-theme;
      name = "Adwaita";
    };

    font = {
      name = "Sans";
      size = 11;
    };
  };

  xdg.configFile."hypr/hyprland.lua".text = ''
    -- Generated from /etc/nixos/home/jose.nix by Home Manager.
    -- Do not edit this file directly.

    hl.monitor({
      output = "eDP-1",
      mode = "2256x1504@60",
      position = "0x0",
      scale = 1.25,
    })

    hl.env("XCURSOR_THEME", "Adwaita")
    hl.env("XCURSOR_SIZE", "24")
    hl.env("HYPRCURSOR_SIZE", "24")

    hl.config({
      general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        layout = "dwindle",

        col = {
          active_border = {
            colors = {
              "rgba(33ccffee)",
              "rgba(00ff99ee)",
            },
            angle = 45,
          },

          inactive_border = "rgba(595959aa)",
        },
      },

      decoration = {
        rounding = 10,
        rounding_power = 2,

        active_opacity = 0.96,
        inactive_opacity = 0.90,

        shadow = {
          enabled = true,
          range = 12,
          render_power = 3,
          color = 0xee111111,
        },

        blur = {
          enabled = true,
          size = 4,
          passes = 2,
          vibrancy = 0.16,
        },
      },

      animations = {
        enabled = true,
      },

      input = {
        kb_layout = "pt",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,

        touchpad = {
          natural_scroll = true,
          tap_to_click = true,
        },
      },

      dwindle = {
        preserve_split = true,
      },

      misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
      },
    })

    hl.curve("easeOutQuint", {
      type = "bezier",
      points = {
        { 0.23, 1.0 },
        { 0.32, 1.0 },
      },
    })

    hl.curve("quick", {
      type = "bezier",
      points = {
        { 0.15, 0.0 },
        { 0.10, 1.0 },
      },
    })

    hl.animation({
      leaf = "global",
      enabled = true,
      speed = 10,
      bezier = "default",
    })

    hl.animation({
      leaf = "windows",
      enabled = true,
      speed = 4.8,
      bezier = "easeOutQuint",
    })

    hl.animation({
      leaf = "fade",
      enabled = true,
      speed = 3.0,
      bezier = "quick",
    })

    hl.animation({
      leaf = "workspaces",
      enabled = true,
      speed = 2.0,
      bezier = "quick",
      style = "fade",
    })

    local mainMod = "SUPER"
    local terminal = "kitty"

    hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
    hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"))
    hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("noctalia msg panel-toggle clipboard"))
    hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("noctalia msg panel-toggle control-center"))
    hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("noctalia msg session lock"))
    hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("noctalia msg window-switcher"))
    hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("noctalia msg screenshot-region"))
    hl.bind(mainMod .. " + SHIFT + CTRL + S", hl.dsp.exec_cmd("noctalia msg screenshot-fullscreen"))

    hl.bind(mainMod .. " + C", hl.dsp.window.close())
    hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
    hl.bind(mainMod .. " + M", hl.dsp.exit())

    hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
    hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
    hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
    hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

    hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
    hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
    hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
    hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))

    for i = 1, 10 do
      local key = i % 10
      hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
      hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
    end

    hl.bind(
      "XF86AudioRaiseVolume",
      hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
      { locked = true, repeating = true }
    )

    hl.bind(
      "XF86AudioLowerVolume",
      hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
      { locked = true, repeating = true }
    )

    hl.bind(
      "XF86AudioMute",
      hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
      { locked = true }
    )

    hl.bind(
      "XF86MonBrightnessUp",
      hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),
      { locked = true, repeating = true }
    )

    hl.bind(
      "XF86MonBrightnessDown",
      hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),
      { locked = true, repeating = true }
    )
  '';

  programs.noctalia = {
    enable = true;
    systemd.enable = true;

    settings.shell.screenshot.annotate = true;
  };
}
